#get:
#  tags:
#  - analytics
#  summary: Get An Metric Definition Config
#  description: Lists an configs for the metric definitions provided as input
#  operationId: get_config_api_v1_metrics_configs
#  parameters:
#  - required: true
#    schema:
#      title: Metric Workflow ID
#      type: string
#      example: 3742_MadStreetDen
#    name: metric_workflow_id
#    in: path
#  responses:
#    '200':
#      description: Successful Response
#      content:
#        application/json:
#          schema:
#            $ref: '../../schemas/MetricsConfig.yaml'
#    '422':
#      description: Validation Error
#      content:
#        application/json:
#          schema:
#            $ref: '../../schemas/HTTPValidationError.yaml'
delete:
  tags:
  - analytics
  summary: Delete Metric Definition Config
  description: This is used to delete the metrics definition config in config registry.
  operationId: delete_config_api_v1_metrics_configs_delete
  parameters:
  - required: true
    schema:
      title: Metric Workflow ID
      type: string
      example: 3754_MadStreetDen
    name: metric_workflow_id
    in: path
  responses:
    '200':
      description: Successful Response
      content:
        application/json:
          schema:
            $ref: '../../schemas/MetricsConfig.yaml'
    '422':
      description: Validation Error
      content:
        application/json:
          schema:
            $ref: '../../schemas/HTTPValidationError.yaml'
put:
  tags:
  - analytics
  summary: Update Metric Definition Config
  description: This is used to update the metrics definition config in config registry.
  operationId: put_config_api_v1_metrics_configs_put
  parameters:
    - required: true
      schema:
        title: Metric Workflow ID
        type: string
        example: 3742_MadStreetDen
      name: metric_workflow_id
      in: path
  requestBody:
    content:
      application/json:
        schema:
          $ref: '../../schemas/MetricsConfigLite.yaml'
    required: true
  responses:
    '200':
      description: Successful Response
      content:
        application/json:
          schema:
            $ref: '../../schemas/MetricsConfig.yaml'
    '422':
      description: Validation Error
      content:
        application/json:
          schema:
            $ref: '../../schemas/HTTPValidationError.yaml'