---
get:
  tags:
    - embedding_configs
  summary: get embedding configs by id
  description: get embedding configs by id
  operationId: getEmbeddingConfigById
  parameters:
    - name: x-correlation-id
      in: header
      description: correlation id to track requests
      schema:
        type: string
    - name: embedding_config_id
      in: path
      description: ID of embedding_config to return
      required: true
      schema:
        type: integer
        format: int64
  responses:
    '200':
      description: successful operation
      content:
        application/json:
          schema:
            type: object
            properties:
              request_id:
                type: string
              correlation_id:
                type: string
              data:
                $ref: '../../schemas/embedding-configs/embedding-config.yaml'
  