title: Rarity post config request
required:
  - use_case
  - config
type: object
properties:
  use_case:
    title: Use Case
    type: string
    description: unique identifier for the client's use case
  config:
    title: Config
    allOf:
      - $ref: rarity_lite.yaml
    description: Rarity config