---
title: ExtractionConfigResponse
type: object
properties:
  status:
    description: status of the request
    type: string
    enum:
      - SUCCESS
      - FAILURE
  request_id:
    description: id to backtrack the request in internal services
    type: string
  correlation_id:
    description: id sent by the caller to backtrack the request
    type: string
  data:
    type: object
    properties:
      extraction_config_id:
        type: string
        title: unique identifier of the extraction config
        example: ''
