get:
  tags:
  - projects
  summary: fetch long term learning status
  description: fetch long term learning status
  operationId: getLTLStatus
  parameters:
  - name: x-correlation-id
    in: header
    description: correlation id to track requests
    schema:
      type: string
  - name: attribute_id
    in: query
    description: to reset learning based on bucket attribute id
    required: true
    schema:
      type: string
  - name: project_id
    in: path
    description: unique identifier of the project
    required: true
    schema:
      type: string
  responses:
    '200':
      description: successful operation
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                description: status of the request
                type: string
                enum:
                - SUCCESS
                - FAILURE
              request_id:
                description: id to backtrack the request in internal services
                type: string
              correlation_id:
                description: id sent by the caller to backtrack the request
                type: string
              data:
                $ref: '../../schemas/projects/train-status.yaml'
    '400':
      description: Validation failures 1. If project is in draft status
      content:
        application/json:
          schema:
            $ref: '../../schemas/errors/failure-response.yaml'
    '404':
      description: returned when project/attribute/session does not exists
      content:
        application/json:
          schema:
            $ref: '../../schemas/errors/failure-response.yaml'
    '500':
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '../../schemas/errors/failure-response.yaml'
