title: AudienceConfigLiteRequest
required:
  - correlation_id
  - data
type: object
properties:
  correlation_id:
    title: Correlation Id
    type: string
    description: correlation_id for the request
  data:
    $ref: 'AudienceConfigLite.yaml'