title: Body_put_config_api_v1_metrics_configs_put
required:
- config
type: object
properties:
  client:
    title: Client
    type: string
    description: unique identifier for the client
  use_case:
    title: Use Case
    type: string
    description: identifier of the use case
    default: metrics
  config:
    title: Config
    allOf:
    - $ref: 'MetricsConfigLite.yaml'
    description: Metrics Configuration
