type: object
properties:
  id:
    type: integer
    readOnly: true
  tag:
    type: string
  config:
    allOf:
    - $ref: 'DeploymentConfig.yaml'
    nullable: true
  parent:
    type: integer
    nullable: true
  created_at:
    type: string
    format: date-time
    readOnly: true
  updated_at:
    type: string
    format: date-time
    readOnly: true
required:
- created_at
- id
- tag
- updated_at
