type: object
properties:
  region:
    allOf:
    - $ref: 'Region.yaml'
    readOnly: true
  deployment:
    allOf:
    - $ref: 'ModelDeploymentsView.yaml'
    readOnly: true
  config_data:
    allOf:
    - $ref: 'Config.yaml'
    readOnly: true
  transport:
    allOf:
    - $ref: 'TransportEnum.yaml'
    readOnly: true
required:
- config_data
- deployment
- region
- transport
