required:
- balance_strategy
- data_buffer_size
- dataset_type
- init_thresh
- sampling_strategy
type: object
properties:
  data_buffer_size:
    type: integer
  init_thresh:
    type: integer
  dataset_type:
    type: string
  balance_strategy:
    type: string
  sampling_strategy:
    $ref: 'reprojection.yaml'
