title: ListConfigsResponse
required:
  - request_id
  - correlation_id
  - status
type: object
properties:
  request_id:
    title: Request Id
    type: string
    description: request_id generated internally
  correlation_id:
    title: Correlation Id
    type: string
    description: correlation_id for the request
  status:
    title: Status
    type: string
    description: status for the request
  data:
    title: Data
    type: array
    items:
      type: object
      additionalProperties:
        $ref: 'TrendingConfigLite.yaml'
    description: configs for given client
    default: []