title: TrendingConfig_Post
required:
  - use_case
  - config
type: object
properties:
  use_case:
    title: Use Case
    type: string
    description: unique identifier for the client's use case e.g. trending_products, trending_buy_counts
  config:
    title: Config
    allOf:
      - $ref: TrendingConfigLite.yaml
    description: TrendingConfig